### ISSUE TITLE
Host the application on a free service like Vercel

### ISSUE THREAD

**Issue by DavidePastore** [ziaboby/tombolata#1]
Hi @ziaboby! It seems a cool project! What if you host it on a free service like Vercel? It should be easy to do. If you want help in this sense just ask! 😄

**Comment by cmminutilli** [comment]
Hi @DavidePastore, thanks for the advice 😃 
I just feel it still need to grow up. After an overall improvement and/or when I will add some features on server side (eg. updates via web socket), Vercel could definitively be worth it.

**Comment by cmminutilli** [comment]
The app is available on Github Pages https://ziaboby.github.io/tombolata/
